#SPDX-License-Identifier: MIT-0
---
# tasks file for mongodb
- name: Set up MongoDB
  block:
    - name: Pull MongoDB image
      become: true
      docker_image:
        name: "{{ mongodb_image_name }}:{{ mongodb_image_tag }}"
        source: pull
      tags: docker_image

    - name: Run MongoDB Container
      docker_container:
        name: "{{ mongodb_container_name }}"
        image: "{{ mongodb_image_name }}:{{ mongodb_image_tag }}"
        ports:
          - "{{ mongodb_port }}:{{ mongodb_port }}"
        volumes:
          - "{{ mongodb_data_dir }}:/data/db"
        networks:
          - name: "{{ mongodb_network }}"
      tags: docker_container, database, backend
  tags: mongodb
