#SPDX-License-Identifier: MIT-0
---
# tasks file for mongodb
# MongoDB Setup
- name: Pull MongoDB image
  become: true
  docker_image:
    name: mongo:4.4
    source: pull

- name: Run MongoDB Container
  docker_container:
    name: yolo-mongo
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - /home/vagrant/sabasaba-mongo-data:/data/db
    networks:
      - name: maandamano-net
  tags:
    - database
    - backend