#SPDX-License-Identifier: MIT-0
---
# tasks file for mongodb
- name: Set up MongoDB
  block:
    - name: Pull MongoDB image
      become: true
      docker_image:
        name: mongo:4.4
        source: pull
      tags: docker_image

    - name: Run MongoDB Container
      docker_container:
        name: yolo-mongo
        image: mongo:4.4
        ports:
          - "27017:27017"
        volumes:
          - /home/vagrant/sabasaba-mongo-data:/data/db
        networks:
          - name: maandamano-net
      tags: docker_container, database, backend
  tags: mongodb
