#This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

#To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

#It's also a requirement to have Docker and the docker-compose plugin installed in your environment

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

version: "3.9"

services:

  #Builds the frontend Docker image and creates the frontend microservice
  mola-yolo-frontend:
    image: molacounsel/yolo-frontend:v1.0.0
    build: ./frontend
    container_name: mola-yolo-frontend
    
    ports:
      - "3000:3000"
    depends_on: 
      - mola-yolo-backend
    networks:
      - maandamano-net

  #Builds the backend Docker image and creates the backend microservice
  mola-yolo-backend:
    image: molacounsel/yolo-backend:v1.0.0
    build: ./backend
    container_name: mola-yolo-backend
    
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
    networks:
      - maandamano-net

  #Creates the database microservice
  mongo:
    image: mongo:8.0.11
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    networks:
      - maandamano-net
    volumes:
      - sabasaba-mongo-data:/data/db

volumes:
  sabasaba-mongo-data:
    driver: local

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  maandamano-net:
    name: maandamano-net
    driver: bridge
    