---
- name: Run MongoDB Container
  docker_container:
    name: app-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./sabasaba-mongo-data:/data/db
    networks:
      - name: maandamano-net
  tags:
    - database
    - backend