#SPDX-License-Identifier: MIT-0
---
- name: Set up Docker service
  block:
    - name: Ensure Docker is installed
      apt:
        name: "{{ docker_package_name }}"
        state: present
      tags: apt

    - name: Ensure Docker is running
      service:
        name: "{{ docker_service_name }}"
        state: "{{ docker_service_state }}"
        enabled: "{{ docker_service_enabled }}"
      tags: service
  tags: docker


