#SPDX-License-Identifier: MIT-0
---
- name: Clone app repository
  block:
    - name: Clone backend repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_version }}"
      tags: git
  tags: clone_repo

