#SPDX-License-Identifier: MIT-0
---
- name: Set up backend service
  block:
    - name: Build backend Docker image
      become: true
      docker_image:
        build:
          path: "{{ backend_build_path }}"
        name: "{{ backend_image_name }}:{{ backend_image_tag }}"
        source: build
      tags: docker_image

    - name: Run backend Docker container
      become: true
      docker_container:
        name: "{{ backend_container_name }}"
        image: "{{ backend_image_name }}:{{ backend_image_tag }}"
        networks:
          - name: "{{ backend_network }}"
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        command: "{{ backend_command }}"
      tags: docker_container
  tags: backend
