#SPDX-License-Identifier: MIT-0
---
- name: Set up Docker service
  block:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      tags: apt

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true
      tags: service
  tags: docker

