#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: true
